### ISSUE TITLE
Put in .htaccess files for per project redirects

### ISSUE THREAD

**Issue by ennru** [akka/akka.github.com#554]
Add `.htaccess` files in the Paradox docs roots of our projects to have a goto-place for configuring renamed pages in the docs.
- [x] akka/akka (already there)
- [x] akka/akka-http (already there)
- [x] akka/alpakka-kafka https://github.com/akka/alpakka-kafka/pull/743
- [x] akka/alpakka https://github.com/akka/alpakka/pull/1574
- [x] akka/akka-management depends on #568
- [x] akka/akka-grpc depends on #561 
- [x] akka/akka-persistence-cassandra depends on https://github.com/akka/akka-persistence-cassandra/issues/133

**Comment by ennru** [comment]
Closing this now. It should be available everywhere.
